### ISSUE TITLE
problème run smartwatts

### ISSUE THREAD

**Issue by lastrecrue** [powerapi-ng/powerapi-ng.github.io#5]
Bonjour quand j’essaie de lancer la formula de mon coté j'ai cette erreur: 
`achraf@achraf-Aspire-E5-571P:~/git/power_api$ sudo docker run smartwatts --config-file config_file_smart_watts.json
Unable to find image 'smartwatts:latest' locally
docker: Error response from daemon: pull access denied for smartwatts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

**Comment by ldesauw** [comment]
Bonjour, 
La commande correcte pour lancer smartwatts depuis docker avec un fichier de configuration est la suivante : 
`docker run -v $(pwd)/config_file.json:/config_file.json powerapi/smartwatts-formula --config-file /config_file.json`
